version: "3"

services:
  bsf-cms:
    image: bsf-admin
    container_name: bsf-cms
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - bsf-cms-network
    ports:
      - "1337:1337"

  bsf-cms-db:
    image: mongo
    container_name: bsf-cms-db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - bsf-cms-network
    volumes:
      - bsf-db-data:/data/db
    ports:
      - "27017:27017"

networks:
  bsf-cms-network:
    driver: bridge

volumes:
  bsf-db-data:
